### ISSUE TITLE
with node 15 it breaks

### ISSUE THREAD

**Issue by gkaizer** [jsoverson/refactor-plugin-common#5]
#### In a test project with just shift-refactor and refactor-common-plugin installed, with this piece of code in index.js:
```javascript
const { refactor } = require('shift-refactor');
const commonMethods = require('refactor-plugin-common');

const src = `var arr1 = ['statsCnt', 'isInteger', 'toLocaleLowerCase', 'keys', 'forceWrap', 'toUpperCase', 'left', 'checked', 'length', 'isKeyed', 'mongoDbMode', 'chknull', 'skipEmpty', 'toJson', 'table', '": ', 'autoNum', 'indexOf', 'getElementById', 'fieldType', 'stringify', 'value', 'join', 'push', 'toNumber', 'isNumeric', 'nullIsNull', 'NULL', 'null', 'parse', 'substr', 'split', 'lineMode'];

var _0x1606 = function(_0x5c5533, _0x52c467) {
    _0x5c5533 = _0x5c5533 - 0x0;
    var _0x160639 = _0x52c4[_0x5c5533];
    return _0x160639;
};`;

const $script = refactor(src, commonMethods);

console.log($script.print());
```
#### running it thows this exception:

*TypeError: plugin is not a function
    at D:\node-projects\esempi-deobfuscations\node_modules\shift-refactor\dist\src\refactor-session-chainable.js:22:33
    at Array.forEach (<anonymous>)
    at new RefactorSessionChainable (D:\node-projects\esempi-deobfuscations\node_modules\shift-refactor\dist\src\refactor-session-chainable.js:21:34)
    at new _a (D:\node-projects\esempi-deobfuscations\node_modules\shift-refactor\dist\src\refactor-session-chainable.js:31:39)
    at Function.create (D:\node-projects\esempi-deobfuscations\node_modules\shift-refactor\dist\src\refactor-session-chainable.js:43:27)
    at refactor (D:\node-projects\esempi-deobfuscations\node_modules\shift-refactor\dist\src\refactor-session-chainable.js:1158:14)
...etc*

#### It can't find plugin(this) as a function

**Comment by gkaizer** [comment]
I tested also in a linux box with node 12, it appears to be something related with how code is transpiled to javascript(?) and not node itself
(I tested it in https://www.katacoda.com/courses/nodejs/playground, same problem)

**Comment by gkaizer** [comment]
it seems that editing refactor-session-chainable.js from:

```javascript
classConstructor.plugins.forEach(plugin => {
            Object.assign(this, plugin(this));
        });
```
to
```javascript
classConstructor.plugins.forEach(plugin => {
            Object.assign(this, plugin[this]);
        });
```
fixed the problem

**Comment by gkaizer** [comment]
Changing to
```javascript
const { commonMethods } = require('refactor-plugin-common');
``` 
seems to work.
